- hosts: vm
  tasks:
  - name: Add repository
    yum_repository:
      name: docker
      description: DOCKER YUM repo
      baseurl: https://download.docker.com/linux/centos/8/x86_64/stable/
      gpgcheck: no

  - name: downloading packages
    command: 
      cmd: "yum install docker-ce --nobest --allowerasing -y"

  - name: starting services
    service: 
      name: docker
      state: started
